export const CIRCLE_CATEGORIES = [
  "Travel",
  "Culture",
  "Language Exchange",
  "Professional",
  "Technology & Startups",
  "Hobbies & Crafts",
  "Sports & Fitness",
  "Arts & Entertainment",
  "Food & Cooking",
  "Music",
  "Gaming",
  "Education & Learning",
  "Volunteering & Causes",
  "Health & Wellness",
  "Parenting & Family",
  "LGBTQ+",
  "Environment & Sustainability",
  "Books & Writing",
  "Photography",
  "Other",
] as const;
