export const LANGUAGES = [
  "English", "Mandarin Chinese", "Hindi", "Spanish", "French",
  "Standard Arabic", "Bengali", "Portuguese", "Russian", "Urdu",
  "Indonesian", "German", "Japanese", "Nigerian Pidgin", "Marathi",
  "Telugu", "Turkish", "Tamil", "Yue Chinese (Cantonese)", "Vietnamese",
  "Korean", "Wu Chinese (Shanghainese)", "Tagalog", "Gujarati", "Persian (Farsi)",
  "Javanese", "Italian", "Hausa", "Bhojpuri", "Amharic",
  "Punjabi", "Kannada", "Sindhi", "Yoruba", "Ukrainian",
  "Malayalam", "Igbo", "Xhosa", "Zulu", "Afrikaans",
  "Swahili", "Polish", "Uzbek", "Malay", "Sundanese",
  "Burmese", "Thai", "Odia", "Maithili", "Awadhi",
  "Dutch", "Romanian", "Azerbaijani", "Nepali", "Sinhala",
  "Khmer", "Greek", "Kazakh", "Hungarian", "Chhattisgarhi",
  "Zhuang", "Somali", "Assamese", "Czech", "Swedish",
  "Hmong", "Belarusian", "Kinyarwanda", "Haitian Creole", "Dari",
  "Serbian", "Hebrew", "Akan (Twi)", "Bulgarian", "Slovak",
  "Finnish", "Danish", "Norwegian", "Croatian", "Georgian",
  "Armenian", "Lithuanian", "Slovenian", "Latvian", "Estonian",
  "Mongolian", "Tibetan", "Lao", "Tigrinya", "Pashto",
  "Kurdish", "Malagasy", "Wolof", "Fula (Fulani)", "Shona",
  "Bambara", "Icelandic", "Maltese", "Welsh", "Irish (Gaelic)",
  "Basque", "Catalan", "Māori", "Samoan", "Fijian",
  "Sign language (any)", "Other / Not listed",
] as const;
