-- AlterEnum
ALTER TYPE "AnalyticsEventType" ADD VALUE 'REVIEW_PROMPT_SHOWN';
ALTER TYPE "AnalyticsEventType" ADD VALUE 'REVIEW_PROMPT_LOVED';
ALTER TYPE "AnalyticsEventType" ADD VALUE 'REVIEW_PROMPT_DECLINED';
ALTER TYPE "AnalyticsEventType" ADD VALUE 'REVIEW_PROMPT_SNOOZED';
